apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-cert  #name of this object
  namespace: default #same namespace as 
spec:
  dnsNames:
    - democrm-mgroszyk.ddns.net
  secretName: example-tls-cert
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer