apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: clusterissuer
spec:
  acme:
    email: maciej.groszyk8@gmail.com
    preferredChain: ""
    privateKeySecretRef:
      name: one-eye-issuer-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx