apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democrm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: ./democrm
    repoURL: 'https://github.com/maciejgrosz/kubernetes-mongodb.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: default
 