version: '2.2'

services:
  maven:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/maciejgroszyklavagna:latest
    container_name: "maven"
    ports:
    - 8080:8080
    networks:
     - mynet
  nginx:
    image: nginx:1.23.1
    container_name: nginx
    restart: always
    ports:
      - 8082:80
    volumes:
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
     - ./maven-data/webapp:/usr/share/nginx/html
     - ./maven-data/webapp/setup/index.html:/usr/share/nginx/html/index.html
    networks:
     - mynet
    depends_on:
     - maven
volumes:
  db:
    driver: local
networks:
  mynet:
    name: mynet